BLOCK_COLORS:
  # デフォルトの色設定
  DEFAULT:
    EMPTY: [0, 0, 0]           # 空のブロック (黒)
    WALL: [128, 128, 128]      # 壁 (グレー)
    I_PIECE: [0, 191, 255]     # I字ブロック (シアン)
    J_PIECE: [65, 105, 225]    # J字ブロック (青)
    L_PIECE: [255, 165, 0]     # L字ブロック (オレンジ)
    S_PIECE: [0, 255, 0]       # S字ブロック (緑)
    Z_PIECE: [220, 20, 60]     # Z字ブロック (赤)
    T_PIECE: [186, 85, 211]    # T字ブロック (紫)
    O_PIECE: [255, 255, 0]     # O字ブロック (黄色)

  # 代替色設定1: パステルカラー
  PASTEL:
    EMPTY: [0, 0, 0]
    WALL: [128, 128, 128]
    I_PIECE: [173, 216, 230]   # ライトブルー
    J_PIECE: [176, 196, 222]   # ライトスチールブルー
    L_PIECE: [255, 218, 185]   # ピーチパフ
    S_PIECE: [144, 238, 144]   # ライトグリーン
    Z_PIECE: [250, 128, 114]   # サーモン
    T_PIECE: [221, 160, 221]   # プラム
    O_PIECE: [255, 255, 224]   # ライトイエロー

  # 代替色設定2: ダークテーマ
  DARK:
    EMPTY: [0, 0, 0]
    WALL: [64, 64, 64]         # ダークグレー
    I_PIECE: [0, 139, 139]     # ダークシアン
    J_PIECE: [25, 25, 112]     # ミッドナイトブルー
    L_PIECE: [255, 140, 0]     # ダークオレンジ
    S_PIECE: [0, 128, 0]       # グリーン
    Z_PIECE: [139, 0, 0]       # ダークレッド
    T_PIECE: [128, 0, 128]     # パープル
    O_PIECE: [184, 134, 11]    # ダークゴールデンロッド

  # 代替色設定3: ネオンカラー
  NEON:
    EMPTY: [0, 0, 0]
    WALL: [128, 128, 128]
    I_PIECE: [0, 255, 255]     # ネオンシアン
    J_PIECE: [0, 100, 255]     # ネオンブルー
    L_PIECE: [255, 100, 0]     # ネオンオレンジ
    S_PIECE: [50, 255, 50]     # ネオングリーン
    Z_PIECE: [255, 20, 147]    # ネオンピンク
    T_PIECE: [200, 50, 255]    # ネオンパープル
    O_PIECE: [255, 255, 50]    # ネオンイエロー