SYSTEM:
  H_BOX: 20
  W_BOX: 20
  N_W: 10
  N_H: 22
  COLORS: [[0, 0, 0],
            [128, 128, 128],
            [0, 191, 255],
            [65, 105, 225],
            [255, 165, 0],
            [0, 255, 0],
            [220, 20, 60],
            [186, 85, 211],
            [255, 255, 0]]
  UPDATE_TIME: 500
MODEL:
  WEIGHTS: None
  OUTPUT_DIR: None
  SIZE_STATE: 221
  SIZE_ACTION: 44
  SIZE_HIDDEN: 128
SOLVER:
  GAMMA: 0.99
  NUM_EPISODES: 800
  BATCH_SIZE: 32 # バッチサイズ
  CAPACITY: 10000 # Replay Memoryに保存するデータの最大量
